- id: doi:10.4271/2014-01-1781
  remove: true

- id: doi:10.4271/2014-01-1776
  remove: true

- id: doi:10.1007/s11249-018-1016-z
  remove: true

- id: isbn:9780791887219
  remove: true

- type: patent
  title: "Management of actuator dynamics in a multiple actuator hard disk drive with an unequal number of heads on the two outer arms of each actuator"
  patent-number: "US11664047B2"
  author:
    - Manoj Keshavan
    - Siddhesh Vivek Sakhalkar
    - Hitoshi Shindo
  issued: "2022-05-31"
  url: "https://patents.google.com/patent/US11664047B2/en"

- type: article
  title: "Data storage device independently driving outer and inner fine actuators"
  author: 
    - Manoj Keshavan
    - Yanning Liu
    - Hitoshi Shindo
    - Siddhesh Vivek Sakhalkar
  issued: "2022-10-25"
  note: "Patents cited: US11482254B2, CN202111350685.9A"
  url: "https://patents.google.com/patent/US11482254B2/en"

- type: patent
  title: "Anchoring structure for improved structural dynamics of actuators in a multi-actuator hard disk drive"
  patent-number: "US11942121B2"
  author:
    - Jung-Seo Park
    - Siddhesh Vivek Sakhalkar
    - Thomas J. Hitchner
    - Arman V. Golgolab
  issued: "2026-03-26"
  url: "https://patents.google.com/patent/US11942121B2/en"
